CLASS_NAMES = {

    0: "Pubescent Bamboo",
    1: "Chinese Horse Chestnut",
    2: "Ixora",
    3: "Chinese Redbud",
    4: "True Indigo",
    5: "Japanese Maple",
    6: "Custerd Apple",
    7: "American Sweetgum",
    8: "Cinnamon",
    9: "Siberian Elm",
    10: "Sourwood Tree",
    11: "Japanese Pittosporum",
    12: "Sweetshrub",
    13: "Camphor Tree",
    14: "Sweet Laurel",
    15: "Cherry Laurel",
    16: "Yew Plum Pine",
    17: "Ginkgo Biloba",
    18: "Crap Myrtle",
    19: "Oleander",
    20: "Olive",
    21: "Sweet cherry",
    22: "Ficus Erecta",
    23: "Neem",
    24: "Peach Tree",
    25: "Sakaki",
    26: "Trident Maple",
    27: "English holly",
    28: "Southern Magnolia",
    29: "Eastern CottenWood",
    30: "Tulip Tree",
    31: "Makrut Lime"
}